services:
  app:
    build: .
    image: visitor-counter-app:1.0
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
